version: '3.1'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'todo'
      MYSQL_ROOT_PASSWORD: '0000'
    expose:
      - 3306
    volumes:
      - mysql_data:/var/lib/mysql
  web:
    build: .
    volumes:
      - .:/home/app
    command: /usr/bin/supervisord
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  mysql_data:
