"""Foreignkey constraint in TodoItem

Revision ID: 8e9323b0cf2b
Revises: a8050a30fc3a
Create Date: 2024-03-20 16:33:41.463240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e9323b0cf2b'
down_revision: Union[str, None] = 'a8050a30fc3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'todo_items', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todo_items', type_='foreignkey')
    # ### end Alembic commands ###
